name: Secret Scanning
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  secret-scanning:
    uses: PrismaPhotonics/github-workflows/.github/workflows/secret-scanning.yaml@main
    secrets: inherit
