name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

concurrency:
  group: {% raw %}${{ github.workflow }}{% endraw %}-{% raw %}${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: lint
          cache-dependency-glob: pyproject.toml

      - name: Install nox
        run: uv pip install nox --system

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|{% raw %}${{ env.pythonLocation }}{% endraw %}|{% raw %}${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}

      - name: Lint code
        run: nox -s lint

  tests:
    timeout-minutes: 10
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v5
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: tests-{% raw %}${{ matrix.python-version }}{% endraw %}
          cache-dependency-glob: pyproject.toml

      - name: Install nox
        run: uv pip install nox --system

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|{% raw %}${{ env.pythonLocation }}{% endraw %}|{% raw %}${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}

      - name: Run tests
        run: nox -s tests-{% raw %}${{ matrix.python-version }}{% endraw %} -- --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v5

      - name: Build package
        run: nox -s build

{%- if cookiecutter.docs  %}
      - name: Build docs
        run: nox -s docs
{%- endif %}
